### ISSUE TITLE
Disk space of protocol_3dfsc.py

### ISSUE THREAD

**Issue by cossorzano** [scipion-em/scipion-em-fsc3d#22]
We are using this protocol and we have observed that it creates many intermediate maps that probably are not needed once the protocol finishes. Would it be possible to delete them at the end? It is currently causing a problem with disk space.

**Comment by azazellochg** [comment]
Fixed now, please have a look

**Comment by cossorzano** [comment]
Great, thank you. Is it on Pypi too?

**Comment by azazellochg** [comment]
Yes, v3.0.9
